### PR TITLE
Resolver configuration exporting

### PR DESCRIPTION
**Pull request by mmisecius**

### CODE REVIEW

**Comment by Karm** [comment]
@mmisecius THX. I have two notes I would like you to look into:

1. Create a separate jar library with Pojos Sinkit and Ispn-dump2proto can depend on.
Ispn-dump2proto build is looking for pojos from Sinkit:
```
[ERROR] /home/karm/Projects/ispn-dump2proto/src/main/java/biz/karms/protostream/threat/task/ResolverThreatTask.java:[42,31] cannot find symbol
[ERROR]   symbol:   class ResolverConfiguration
[ERROR]   location: class biz.karms.protostream.threat.task.ResolverThreatTask
[ERROR] /home/karm/Projects/ispn-dump2proto/src/main/java/biz/karms/protostream/threat/task/ResolverThreatTask.java:[127,84] cannot find symbol
[ERROR]   symbol:   class Policy
[ERROR]   location: class biz.karms.protostream.threat.task.ResolverThreatTask
```
Furthermore, it does not have defined dependency on Gson...?

2. Pls, either make sure it builds on its own or it is documented in [README.md](./README.md) what to do with it so as it builds.

Thank you for amending the PR.  :slightly_smiling_face:

**Comment by mmisecius** [comment]
1) I don't understand the mentioned error. The required dependency is sinkit-core-ejb.jar - from which are coming ejb/rest entities which are used in this project as well. I got that would be nicer to be in separate module, let's say 'sinkit-core-domain' on which would depend all other 'modules/projects' sinkit-core-ejb, sinkit-rest, ..., dump2proto' This is 'just' about domain entities.  Further you have hard copied MyProvider...  SinkitCacheName and others which bring real redundancy. These should be clean up firstly

2) Gson is in the test scope - and the purpose is just to deserialize **.json** test resources to be used in 'pseudo integration test'
